### PR TITLE
Webhooks now display Whatsapp profile pic

### PR DESCRIPTION
**Pull request by itspacchu**
- Added support for whatsapp profile pics to now be displayed instead of blank avatar
- Also slicing whatsapp messages to 1000 char long as its causing the bot to crash.

unknown

### CODE REVIEW

**Comment by spookycookie27** [comment]
works for me - just checked. nice!

**Comment by agamsol** [comment]
I'm running the latest version but i don't know why i see the messages webhooks just default discord logo

**Comment by FKLC** [comment]
Hi, thank you for your contribution to the project. I see people used your version as mine was deprecating. I changed the Whatsapp library used in the project and can no longer merge this. I'm sorry for rejecting your pull request and thank you for contributing to the project.

**Comment by agamsol** [comment]
Thank you very much for making this project. Its a great idea. more effort and it would have been getting even more stable and customizable!

Again thank you so much.

sincerely, Agam

**Comment by itspacchu** [comment]
> Hi, thank you for your contribution to the project. I see people used your version as mine was deprecating. I changed the Whatsapp library used in the project and can no longer merge this. I'm sorry for rejecting your pull request and thank you for contributing to the project.

yeah the new multidevice beta breaks the original revengg sadly

**Pull request closed without merging**
